name: vulnerability scan workflow

on: [push, workflow_dispatch]

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@packaged-client-fallback-usage
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                cli_args: "" #[ Meterian CLI Options ]
